### ISSUE TITLE
Sum of expression lamba on List

### ISSUE THREAD

**Issue by TheoVC** [codingseb/ExpressionEvaluator#104]
Hi 

I was trying to make an evaluation, a Sum on a List, but I'm getting an error: CodingSeb.ExpressionEvaluator.ExpressionEvaluatorSyntaxErrorException: 'Function [Sum] unknown in expression : [Sum(x => x.Nombre == "uno" ? (x.Valor ?? 0m) : 0m)]'

What am I doing wrong? or it is not supported?

```
var Lista = new List<Test>() { new Test { Nombre = "uno", Valor = 1.11m }, new Test { Nombre = "uno", Valor = 2.22m }, new Test { Nombre = "uno", Valor = null }, new Test { Nombre = "dos", Valor = 3.33m } };
string script = "Sum(x => x.Nombre == \"uno\" ? (x.Valor ?? 0m) : 0m)";

ExpressionEvaluator Eval = new ExpressionEvaluator()
{
      StaticTypesForExtensionsMethods = new List<Type> { typeof(Enumerable) },
      Namespaces = new List<string>() { "System", "System.Linq"},
      OptionVariableAssignationActive = false, 
      OptionPropertyOrFieldSetActive = false, 
      CacheTypesResolutions = true
};

Eval.Context = Lista;

var result = Eval.Evaluate(script);

// ***********************************************************************
public class Test
{
     public string Nombre { get; set; }
     public decimal? Valor { get; set; }
}
```

**Comment by codingseb** [comment]
Hello @TheoVC I will try to correct this asap. Apparently it does'nt work when list is set as context but when I tested it with list set as variable it return an `int`. I just need to find why it doesnt work the same with context. I already know that indexing do not work with context so I think for now extensions methods either.

```c#
var Lista = new List<Test>() { new Test { Nombre = "uno", Valor = 1.11m }, new Test { Nombre = "uno", Valor = 2.22m }, new Test { Nombre = "uno", Valor = null }, new Test { Nombre = "dos", Valor = 3.33m } };
string script = "Lista.Sum(x => x.Nombre == \"uno\" ? (x.Valor ?? 0m) : 0m)";

ExpressionEvaluator Eval = new ExpressionEvaluator()
{
    CacheTypesResolutions = true
};

Eval.Variables["Lista"] = Lista;

var result = Eval.Evaluate(script);

Eval.Variables["Lista"] = Lista;

var result = Eval.Evaluate(script); //return 3

// ***********************************************************************
public class Test
{
     public string Nombre { get; set; }
     public decimal? Valor { get; set; }
}
```

**Comment by TheoVC** [comment]
Hello codingSeb

maybe if the keyword "this" could be introduced, and work as in regular c#
"this" refer to the Context, por example if the Context is an Array... you could evaluate something like this:

this[0]
this[0].Name

**Comment by TheoVC** [comment]
maybe the "this" keyword could work exactly like a variable... a default variable that is setted every time the Context is changed and point to the Context itself

**Comment by codingseb** [comment]
Yes the `this` keyword idea is the solution because in C# we can not use extention methods neither inding on current object without `this` keyword. Thanks for your suggestion

**Comment by codingseb** [comment]
new version 1.4.30.0 introduce the this keyword to manage extention methods and indexing on Context.
Thanks @TheoVC.

**Comment by TheoVC** [comment]
Hi

Yes I tested and it's working perfectly fine. it's the perfect solution for indexing... and for calling context methods...

```
var Lista = new List<Person>() { new Person { Name = "uno", Value = 1.1m }, new Person { Name = "dos", Value = 2.2m } };

var Eval = new ExpressionEvaluator();
Eval.Context = Lista;
var temp = Eval.Evaluate("10.5m + this.Sum(x => x.Value) + this[0].Value");
```
Actually this code is in production already... :)
