### ISSUE TITLE
Problems with null and inexistent properties, Exception not handled

### ISSUE THREAD

**Issue by TheoVC** [codingseb/ExpressionEvaluator#105]
Something is broken handling nulls and inexistent variables

if Name has a valid string, everything is ok, but if Name is null an exception should be triggered but it doesn't
and if instead of Name you call some other property (inexistent) an exception should be triggered too but it doesn't

the problem happens when the expression is compossed with some elements

```
Eval.Context = new { Person = new Person { Name = null, Value = 1.11m } };
try
{
     var result2 = Eval.Evaluate("\"test one \" + Person.Name.Trim()");
     var result3 = Eval.Evaluate("\"test two\" + Person.AnotherName.Trim()"); 
}
catch(Exception e)
{
    // no exception is triggered
     Console.WriteLine(e.Message);
}


//****************************************************
public class Person
{
    public string Name { get; set; }
    public decimal? Value { get; set; }
}
```

**Comment by TheoVC** [comment]
I think is a problem processing the stack

**Comment by codingseb** [comment]
Thanks for opening theses issues @TheoVC 
I will look about that asap.

**Comment by TheoVC** [comment]
any news?

**Comment by codingseb** [comment]
It's for very soon. Sorry I had just some weeks with less free time for EE.

**Comment by codingseb** [comment]
This issue is already OK in dev branch. Just need to do #104 before next version

**Comment by codingseb** [comment]
The new version 1.4.30.0 Correct this issue thanks again.

**Comment by TheoVC** [comment]
Thanks to you... this library is awesome...
