### ISSUE TITLE
[suggestion] AssignVariable : Convert value type according to the target variable's type

### ISSUE THREAD

**Issue by froggy96** [codingseb/ExpressionEvaluator#115]
Dear,

Exception occurs when I declare a variable: 
ushort WORD;

and then assign a value:
WORD = 1;

Because 1 is typed as 'int' not 'ushort';

So I suggest AssignVariable function to be changed like below:
With this, I may assign value as follows:
ex1) WORD = 1; (OK)
ex2) WORD = 10.1; (OK, value is 10, the variable type still remains as ushort)
ex2) WORD = "10"; (OK, value is 10, the variable type still remains as ushort)

But still throw exceptions for followings:
WORD = 65536; (Overflow Exception)
WORD = "ABCD"; (Format Exception)

        protected virtual void AssignVariable(string varName, object value)
        {
            if (Variables.ContainsKey(varName) && Variables[varName] is StronglyTypedVariable stronglyTypedVariable)
            {
                if (value == null && stronglyTypedVariable.Type.IsValueType && Nullable.GetUnderlyingType(stronglyTypedVariable.Type) == null)
                {
                    throw new ExpressionEvaluatorSyntaxErrorException($"Can not cast null to {stronglyTypedVariable.Type} because it's not a nullable valueType");
                }

                Type typeToAssign = value?.GetType();
                if (typeToAssign == null || stronglyTypedVariable.Type.IsAssignableFrom(typeToAssign))
                {
                    stronglyTypedVariable.Value = value;
                }
                **else
                {
                    try
                    {
                        Variables[varName] = Convert.ChangeType(value, stronglyTypedVariable.Type);
                    }
                    catch
                    {
                        throw new InvalidCastException($"A object of type {typeToAssign} can not be cast implicitely in {stronglyTypedVariable.Type}");
                    }**
                }
            }
            else
            {
                Variables[varName] = value;
            }
        }

**Comment by codingseb** [comment]
Thanks @froggy96 for this issue. Your correction is published in the version 1.4.32.0

**Comment by froggy96** [comment]
Thanks a lot!
I'd like to say that this library is great. It eliminated my months-long headaches!!!
