### ISSUE TITLE
Raise ExpressionEvaluatorSyntaxErrorException while declaring a variable with the prefix "new"

### ISSUE THREAD

**Issue by guyleaf** [codingseb/ExpressionEvaluator#116]
## Problem
Declaring a variable with the prefix "new" will cause an exception.
The evaluator will identify it as new instance behavior.

## Reproduce
Demo: https://dotnetfiddle.net/LwThhc

Thanks,
guyleaf

**Comment by guyleaf** [comment]
I fixed it in PR #117.

**Comment by codingseb** [comment]
Your PR has been merged and is live in version 1.4.32.0.
Thanks for it.
