### ISSUE TITLE
Evaluating "new DateTime(2022,1,20)" does not work unless OptionInlineNamespacesEvaluationActive is turned on

### ISSUE THREAD

**Issue by HelgeL** [codingseb/ExpressionEvaluator#127]
Still using this fantastic library and great to see it progresses! I have made a huge version jump from 1.4.12.0 to current 1.4.35.0. However one of my tests does not pass anymore, so I have fiddled around.

When evaluating this expression:
`new DateTime(2022,1,20)`
the result is correctly evaluated with `OptionInlineNamespacesEvaluationActive=true`.

However when `OptionInlineNamespacesEvaluationActive=false` (which was my default setting), an error is raised as follows:
`Type or class DateTime is unknown`

 The old version could successfully evaluate this expression regardless of OptionInlineNamespacesEvaluationActive setting. Maybe it is on purpose in which case I'm fine with turning the option on. I was just hesitating with the possible performance and security implications.

**Comment by codingseb** [comment]
Hello @HelgeL thanks for the issue.
Yes this is a bug introduced during the evolution of ExpressionEvaluator.

It should work again in version 1.4.36.0

**Comment by HelgeL** [comment]
Wow, Grüezi and thank you for your quick fix! That's awesome. (Can I donate somehow?)
Btw if you are interested, I have forked your repo and have enhanced ExpressionEvaluator to handling single quoted strings. Would you be interested? I could prepare a pull request, or you can see my commits from yesterday here: https://github.com/HelgeL/ExpressionEvaluator/commits/master

**Comment by HelgeL** [comment]
Found the donate button, never mind!

**Comment by codingseb** [comment]
WOW thanks a lot @HelgeL for your donation

**Comment by codingseb** [comment]
> I have forked your repo and have enhanced ExpressionEvaluator to handling single quoted strings. 
Would you be interested? I could prepare a pull request, or you can see my commits from yesterday here: https://github.com/HelgeL/ExpressionEvaluator/commits/master

Can be useful.

I see that it is an option so normally it should not break compatibility. Just some questions : 
Do you have some tests that come with ?
Did you try it with char  evaluation that use also singlequote. how do you mange potential conflicts ?
You just always use the option `evaluator.OptionCharEvaluationActive = false;` when `evaluator.OptionSingleQuotedStringEvaluationActive= true;` or you can use both together ?

We just should add some documentation on it.
