### ISSUE TITLE
EvaluateInstanceCreationWithNewKeyword doesn't support arrays

### ISSUE THREAD

**Issue by guylando** [codingseb/ExpressionEvaluator#14]
`"".Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries)`
throws error in EvaluateInstanceCreationWithNewKeyword method "No '(' found after..."
same for 
`"".Split(new char[1] { ',' }, StringSplitOptions.RemoveEmptyEntries)`

any quick workaround?

**Comment by guylando** [comment]
`"".Split((new List<char>() { ',' }).ToArray(), StringSplitOptions.RemoveEmptyEntries)`
throws Object reference not set to an instance of an object.

**Comment by guylando** [comment]
"".Split(Array(',').Select(item => (char)item).ToArray(), StringSplitOptions.RemoveEmptyEntries)
fails too, the object[] array GetMethod does not find the linq extension method "Select"

**Comment by guylando** [comment]
`"".Split(List(',').Select(item => (char)item).ToArray(), StringSplitOptions.RemoveEmptyEntries)`
fails too

**Comment by guylando** [comment]
@codingseb any help please? All I wanted is to just split a string...

**Comment by guylando** [comment]
"".Split(",".ToCharArray(), StringSplitOptions.RemoveEmptyEntries) worked as a workaround

**Comment by codingseb** [comment]
Hi I am at work for now and I develop ExpressionEvaluator in my spare time.
I will look to add support for typed arrays when I have some time.

Thanks for sharing your workaround

**Comment by guylando** [comment]
Thanks, great project. Better than the alternatives because of the simplicity of use and because the code fits in one cs file.

**Comment by codingseb** [comment]
I just added a new function ArrayofType to manage at least string split (some example are added in the readme.

A better support of types, generics, array and collections creation are on my todo list.

For now I consider this issue closed.
