### ISSUE TITLE
Match function arguments considering implicit casts

### ISSUE THREAD

**Issue by israellot** [codingseb/ExpressionEvaluator#148]
If I have a function signature like `function(string a, TypeWithImplicitCastOperatorToString b)` and I call it with `function("bla","bla")` the evaluator does not match.

**Comment by codingseb** [comment]
Version 1.4.39.0 is available it contains your pull request.
Thanks a lot for your contribution

**Comment by israellot** [comment]
Thanks for considering @codingseb ! And Thanks for sharing this repo, it has been very useful.
