### ISSUE TITLE
NetStandard compatibility

### ISSUE THREAD

**Issue by PhenX** [codingseb/ExpressionEvaluator#15]
Hello, thanks for this great lib, is the support for NetStandard / dotnet core something we can wait for ?

**Comment by codingseb** [comment]
Hello,
I personally use it only in .NetFramework stuff until now
I will look what it takes to do it in the nuget.
For now, did you try to just copy the ExpressionEvaluator.cs in a .net standard or core project ?

**Comment by PhenX** [comment]
I tried to convert it to visual studio 2017 then convert the project to net
standard 2.0 without trouble (except the testing ui) , I'll make a PR soon.

**Comment by PhenX** [comment]
Great ! Thank you for the new nuget package too :)

Greetings from France !

**Comment by codingseb** [comment]
Merci et salutations de Suisse ;)
