### ISSUE TITLE
missing variable classOrTypeName

### ISSUE THREAD

**Issue by Thrakon** [codingseb/ExpressionEvaluator#2]
Hi!

I'm trying to see if your libraries fits my needs.

When i import the .cs file to my project, i get an error in the file on lines 282 and 283 that "classOrTypeName" does not exist in the current context.

Am i missing something?

**Comment by codingseb** [comment]
Hello Thanks for your interest.
It seems that I commited Something wrong.
I am sorry about that.

Note also that, I am currently working on some improvements of this evaluator and I will probably integrate it in a Nuget package soon.

For now I will just create a dev branch to not break master each time I try something new.
