### ISSUE TITLE
Issue when parsing Decimal number

### ISSUE THREAD

**Issue by Vertygo** [codingseb/ExpressionEvaluator#22]
If your regional settings has decimal separator other than `.` you will end up with an exception. `numberRegex` should be changed to take care of culture settings.

https://github.com/codingseb/ExpressionEvaluator/blob/682addc3162bf9a29296453fad17818da7f0023b/CodingSeb.ExpressionEvaluator/ExpressionEvaluator.cs#L34

**Comment by Vertygo** [comment]
[Flee](https://github.com/mparlak/Flee) library has a really good solution for this example. It gives you the ability to set different culture or to set custom decimal separator + functional/command separator `FunctionArgumentSeparator`.

**Comment by codingseb** [comment]
OK thanks for the input.
The actual solution I implemented is to add 3 options. `OptionNumberParsingDecimalSeparator`, `OptionFunctionArgumentsSeparator` and `OptionInitializersSeparator`.
As a goal of ExpressionEvaluator is to have a syntax near C# default values will be :
* `OptionNumberParsingDecimalSeparator = "."`
* `OptionFunctionArgumentsSeparator = ","`
* `OptionInitializersSeparator = ","`

And the culture to evaluate numbers is a copy of CultureInvariante with just NumberFormat.NumberDecimalSeparator set to OptionNumberParsingDecimalSeparator.  

I think this solution allow to be enough flexible for now. What do you think ?
It is already available on [dev branch](https://github.com/codingseb/ExpressionEvaluator/tree/dev) and will be Available in version 1.3.4

**Comment by Vertygo** [comment]
Looks good! Maybe I'm nitpicking now but I'm also interested if it would be hard to have thousands separator? I think that would cause a lot of pain since it would cause breaking change - you would have to force `OptionFunctionArgumentsSeparator` to be something like `;` by default.

**Comment by codingseb** [comment]
I will add an other option for this. But All these options will need to be changed manually and if you use them to be changed to avoid conflict. As I wrote already the goal is to keep ExpressionEvaluator as near as possible of the C# syntax by default.  
 
For the thousands separator. I will look if I can integrate it in the numberRegex or if I need to switch to an another one. The Regex already changed in dev branch to add the C# 7 `_`[digit separator](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-7.0/digit-separators) so it's an another conflict risk.

Next version will also support hexadecimal and binary notations for numbers and these two have already an other dedicated Regex. So maybe I will add an other Regex and switch to it if these options are used. So it will have a C# way to write numbers and a more culture dependent way to write it.

**Comment by codingseb** [comment]
I am trying. But in my tests if I put a ' (single quote) for thousand separator I have also conflicts with the interpretation of char values 'a' ,'b' ...

Of course you can unactive char evaluation with the already existing option `evaluator.OptionCharEvaluationActive = false` . But I think it become tricky to culture dependant evaluation for numbers.
In addition to that dependending of what separators you use you will also have conflicts with some operators like | ! and maybe others.

So will already add these options and a `CultureInfoForNumberParsing` Property. But for now use it at your own risks.

And later I will maybe add other options or functionalities to drive better the way things are evaluated.

**Comment by codingseb** [comment]
OK so for the specific case of using single quotes as separators. I found a better way to evaluate chars so they are not in conflict anymore. The `evaluator.OptionCharEvaluationActive = false` is not needed anymore

**Comment by Vertygo** [comment]
That sounds great @codingseb. Do you have it in dev branch to try it out?

**Comment by codingseb** [comment]
Yes it is dev.

**Comment by codingseb** [comment]
I just published version 1.3.4.0 that include all of this.
If you have some improvements to submit don't hesitate.
it will be included in next release.

Otherwise, can I consider this issue as closed ?
