### ISSUE TITLE
Ensure Type 'double' though all calculated values

### ISSUE THREAD

**Issue by Smartis2812** [codingseb/ExpressionEvaluator#25]
Hey there,

If I try to evaluate ```(130-120)/(2*250)``` I get ```0``` instead of ```0.02```.
I´ll deep dive into this, but maybe someone already stumble across this.

Update:
After looking at the code, I´ll guess the problem is that after the first cycle of evaluating my expression, the values are ```int``` and in the next cycle the division will happen with two ```int```´s. And that´s why I get no ```double``` Value.

Is there a Way to ensure all calculated Values are ```double``` Values?

Thanks for your response.

**Comment by codingseb** [comment]
Hello yes. Like you figured out.
It use C# Syntax so as long as you have only int values it will execute an int operation.

If you just add a d suffix or a .0 after at least one of your values it will interpret it as double operation.

But I understand your concern when you use it just for small operations.

So I will append a option to evaluate numbers as double by default in next version.

**Comment by codingseb** [comment]
I Just published version 1.3.5.0 that implement the new option [OptionForceIntegerNumbersEvaluationsAsDoubleByDefault](https://github.com/codingseb/ExpressionEvaluator/wiki/Options#optionforceintegernumbersevaluationsasdoublebydefault)
