### ISSUE TITLE
using logical expression without parent doesn't work

### ISSUE THREAD

**Issue by kasajian** [codingseb/ExpressionEvaluator#26]
Try this:
        P1 = 5;
        P2 = 6;
        P1 < 1 && P2 > 3;

**Comment by codingseb** [comment]
Yes your are right it is weird.
I will look for debug that.

**Comment by codingseb** [comment]
OK it was a conflict between < and > operators and the way that generic types was parsed.
The correction is to change the generics parsing.
The correction is already available in the dev branch and will be include in next release (1.3.5.0)

**Comment by codingseb** [comment]
I Just publish version 1.3.5.0
