### ISSUE TITLE
Why are operators limited to "two" characters ?

### ISSUE THREAD

**Issue by kasajian** [codingseb/ExpressionEvaluator#27]
Method name "EvaluateTwoCharsOperators" implies it.

If one were to add "And" and "Or" operators as aliases for && and ||, the current implementation wouldn't work because "And" has three characters.

Making this change seems to work, but not sure it's the best way:

*BEFORE*

        private bool EvaluateTwoCharsOperators(string expr, Stack<object> stack, ref int i)
        {
            if (i < expr.Length - 1)
            {
                string op = expr.Substring(i, 2);
                if (operatorsDictionary.ContainsKey(op))
                {
                    stack.Push(operatorsDictionary[op]);
                    i++;
                    return true;
                }
            }

            return false;
        }

*AFTER*

        private bool EvaluateTwoCharsOperators(string expr, Stack<object> stack, ref int i)
        {
            if (i < expr.Length - 1)
            {
                string op = expr.Substring(i, 2);
                var containsKey = operatorsDictionary.ContainsKey(op);
                if (!containsKey && expr.Length >= i + 3)
                {
                    op = expr.Substring(i, 3);
                    containsKey = operatorsDictionary.ContainsKey(op);
                }
                if (containsKey)
                {
                    stack.Push(operatorsDictionary[op]);
                    i += op.Length - 1;
                    return true;
                }
            }

            return false;
        }

**Comment by codingseb** [comment]
Ok. I need to think a little about this one.
I didn't provide that somebody want to change operators.

I will also check if operators like `or and` are not in conflict with the way it parse and evaluate variables.

**Comment by kasajian** [comment]
I guess I am making the assumption that this evaluator is meant to allow one to tweak the syntax depending on need.   But Maybe that's wrong and this is really supposed to be primarily a C# syntax evaluator.

I need an evaluator that has a preexisting defined syntax -- and it's a combination of BASIC and C where you have both && and 'and', || and 'or', also both "=" and "==" work.   There's no assignments -- just expressions.

So I think there's a decision to be made here.   Decide that this code-base is not fit-for-purpose for my needs, Or, put the code-base on a path such that some of these things are user-extensible.   For instance, perhaps some future version of the library can allow for the above mentioned changes be configured dynamically rather than change the source.

**Comment by codingseb** [comment]
Yes. The goal of this evaluator is to be as near as C# by default.

But you can of course try to adapt it to your need if it works.

I think modify existing operators is quite easy but you need to modify ExpressionEvaluator file itself as you say. If a way to modify or extend how operators works from outside of the file could exists it would be better. It could be also easier to update the library. So I will think about it for future versions.

At first EvaluationExpression was just a small thing that I made for my own needs. I just decided at some point to share it so it can maybe help others. I appreciate ideas like yours because it help this project to live. It's just that I didn't think about this specific idea until now.
So it will probably take some time until something fully extensible will be available.
And it will also probably need some deeper changes and refactoring of the lib.

**Comment by codingseb** [comment]
Just to keep track of some ideas related to it :
* Add a way to allow  aliases for existing operators like `Or, And`
* Add a way to add some custom operators and corresponding implementations
* Flexible length of the operators
* Types : multiple operands vs Single operands  (Maybe start with only 2 operands operators)
* Take care of operators precedences (priorities)

*Examples* :
```C#
x love y;
a kill b;
Not v;
~?variable;
c @+ h;
a @ b # c;
//...
```

**Comment by kasajian** [comment]
Yes, very cool.   I also like the fact that it's all in one file.   thanks.

**Comment by codingseb** [comment]
OK I think the new release [1.4.0.0](https://github.com/codingseb/ExpressionEvaluator/releases/tag/1.4.0.0) resolve this issue. [See this for more infos](https://github.com/codingseb/ExpressionEvaluator/wiki/Advanced-Customization-and-Hacking)
