### ISSUE TITLE
ExpressionEvaluator method should use IDictionary or IReadOnlyDictionary input type

### ISSUE THREAD

**Issue by kasajian** [codingseb/ExpressionEvaluator#29]
Small request.

The "ExpressionEvaluator()" method that takes a Dictionary of variables, I'd like to suggest that it instead take IDictionary or, better yet, IReadOnlyDictionary.   The reason is because the host code may already have a set of "variables" in a dictionary but the "value" item of each entry is not the variable value, but a different object that contains the value, in addition to other things.   Passing that directly to your code wouldn't work because your code expects the Value of the dictionary entry to be an actual intrinsic value such as an int or a double.   So today, I have to create a separate dictionary just for the evaluator which is wasteful.   If the ExpressionEvaluator code took on an interface instead, I could implement that interface in my object that used the existing dictionary internal to our code.

In general, parameters to methods should be the least simplest form that the code requires.  So if your code isn't going to add items to the dictionary, than IReadOnlyDictionary<string, object> is all you need to require.

**Comment by codingseb** [comment]
It's done in dev branch. Will be available in v : 1.3.6.0

It's IDictionary<string, object> because when you do : 
```c#
x = 5
```
it actually put `x` in Variables Dictionary.
*Yes I know it's not necessary the best solution and variables scoping is done the wrong way.
But it was the easy way for now.
I still have some improvements in my todo list related to variables management*

**Comment by codingseb** [comment]
Version 1.3.6.0 is avaiable.

**Comment by kasajian** [comment]
I understand that this is not supposed to be a fully sophisticated system,
but it's impressive for what it is.   The reason I like it is because of
it's simplistic nature.   I'm not planning on using it in production -- but
it's create for quick&dirty research work.
