### ISSUE TITLE
Added a righthandOperator 'Not' does not work

### ISSUE THREAD

**Issue by markvdkerkhof** [codingseb/ExpressionEvaluator#37]
I tried to create a new righthand operator named "Not" which does exactly the same as ExpressionOperator.LogicalNegation
But it will fail because the function 'EvaluateVarOrFunc' throws an error like 
"Variable [Not] unknown in expression : []");

I think the problem is that 'Not' is a string and because of that it will be tried to parse it to a function in steat of an operator.
Maybe a solution could be to add on line 1716:
 ` && !operatorsDictionary.ContainsKey(varFuncMatch.Groups["name"].Value)`

**Comment by codingseb** [comment]
Hello, thanks for this issue.
I will look to resolve that.

**Comment by codingseb** [comment]
OK it should be right now, I publish version 1.4.1 with this correction.
Thanks again.
