### ISSUE TITLE
Extended Methods

### ISSUE THREAD

**Issue by TheoVC** [codingseb/ExpressionEvaluator#44]
this a complete library... one of the best I've seen. the only feature that is missing is support for extended methods.

for example. I declare this class

```
public static class MyAuxiliarMethods
{
    public static string MyExtendedMethod(this string str)
    {
        return str + " extended";
    }
}
```

then I should add this type somewhere so all the exteded methods became registered.
or maybe just adding the corresponding namespace...

then I could evaluate an expression like this:

`AnStringVariable.MyExtendedMethod()`

**Comment by codingseb** [comment]
Hello @TheoVC, thanks for your issues.
For this one a solution already exists but I didn't documented this yet: 

```
    public static class StringExtendedMethods
    {
        public static string AddExtended(this string str)
        {
            return str + " extended";
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            ExpressionEvaluator evaluator = new ExpressionEvaluator(new Dictionary<string, object>()
            {
                { "x", "Test" }
            });

            evaluator.StaticTypesForExtensionsMethods.Add(typeof(StringExtendedMethods));

            Console.WriteLine(evaluator.Evaluate("x.AddExtended()"));
        }
    }
```

I will update the documentation

**Comment by codingseb** [comment]
I added some documentation about [Extension method](https://github.com/codingseb/ExpressionEvaluator/wiki/Variables-and-Functions#extension-methods) on the wiki
