### ISSUE TITLE
Ternary expression when condition True has a Bug 

### ISSUE THREAD

**Issue by buweixiaomi** [codingseb/ExpressionEvaluator#53]
Expression: ` 1==1?true:false`  run will show exception.
Code in function "EvaluateTernaryConditionalOperator" under  `s2.Equals(":")`:
` stack.Push(condition ? Evaluate(restOfExpression.Substring(1, j-1)) : Evaluate(restOfExpression.Substring(j + 1)));`
replace with
` stack.Push(condition ? Evaluate(restOfExpression.Substring(0, j)) : Evaluate(restOfExpression.Substring(j + 1)));`
It will be work.

**Comment by codingseb** [comment]
Hello @buweixiaomi, thanks for this issue. I just published Version 1.4.11.0 of ExpressionEvaluator with your correction.
