### ISSUE TITLE
Evaluate methods names as delegates : (calls to Array.ConvertAll() failing)

### ISSUE THREAD

**Issue by mgwilliam** [codingseb/ExpressionEvaluator#98]
When I try the following code:

    var evaluator = new ExpressionEvaluator
    {
        Variables = new Dictionary<string, object>()
        {
            {"values", "1,2,3,4,5,6,-1"}
        }
    };

    var script = "var numbers = Array.ConvertAll(values.Split(','), Int32.Parse); return numbers.Min();";

    return evaluator.ScriptEvaluate(script);

...it fails with the error:

    [System.Array] object has no Method named "ConvertAll".

Should this work?

**Comment by codingseb** [comment]
Hello, @mgwilliam.
Thanks for this issue.
Yes we are at the limit of what ExpressionEvaluator (EE) can do here.  
EE can not evaluate `Int32.Parse` as a `delegate` for now. And as everything is evaluate on the fly it can not select the good override of the method `ConvertAll`. 
I will look what it takes to make EE evaluate Methods names as delegates to allow your kind of writing of this.

So for now a way to write it that work for me is :
[Live Example here](https://dotnetfiddle.net/6FEPZA)
```c#
var evaluator = new ExpressionEvaluator
{
    Variables = new Dictionary<string, object>()
    {
        {"values", "1,2,3,4,5,6,-1"}
    }
};

var script = "var numbers = Array.ConvertAll(values.Split(','), s => Int32.Parse(s)); return numbers.Min();";

return evaluator.ScriptEvaluate(script);
```

**Comment by mgwilliam** [comment]
Thanks for the response.
The suggested code will work fine for what I need, thank you.

**Comment by codingseb** [comment]
Version 1.4.27.0 Manage methods names as methods groups and manage the writing of this issue.
Thanks for this issue @mgwilliam
